set(_AMENT_PACKAGE_NAME "test_tool")
set(test_tool_VERSION "0.0.0")
set(test_tool_MAINTAINER "maddy <madjeeve123@gmail.com>")
set(test_tool_BUILD_DEPENDS )
set(test_tool_BUILDTOOL_DEPENDS "ament_cmake")
set(test_tool_BUILD_EXPORT_DEPENDS )
set(test_tool_BUILDTOOL_EXPORT_DEPENDS )
set(test_tool_EXEC_DEPENDS )
set(test_tool_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(test_tool_GROUP_DEPENDS )
set(test_tool_MEMBER_OF_GROUPS )
set(test_tool_DEPRECATED "")
set(test_tool_EXPORT_TAGS)
list(APPEND test_tool_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
