# goal

string polygon_frame_id
geometry_msgs/Polygon polygon
geometry_msgs/PoseStamped goal_pose
string behavior_tree

iris_interfaces/NavigationMode mode
---
# result

uint16 NONE=0
uint16 INVALID_POLYGON_POINTS=1
uint16 INVALID_COORD_POINTS=2

uint16 result
---
# feedback

geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
float32 distance_remaining