#include "mainwindow.h"
#include "ui_mainwindow.h"
#include <iostream>
#include <QProcess>
#include <QListWidget>
#include <QListWidgetItem>
#include <QDebug>
#include <QString>
#include <QDebug>


using namespace std::chrono_literals;

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow)//This is a class auto-generated by Qt
                                                //Comes from your .ui file 
{
    ui->setupUi(this);
    connect(ui->listWidget, &QListWidget::currentRowChanged, // Sidebar → Page Switching
            this, [=](int row){
                pages(row);
    });
    ui->listWidget->setCurrentRow(0); //Default page

    qtros = std::make_shared<Qtros>();
    connect(qtros.get(),&Qtros::logReceived,this,&MainWindow::onLogReceived);// once the message is received from the subscription in qtros, 
    // it will emit a signal logReceived which is connected to the onLogReceived slot in MainWindow.

    connect(ui->node_list,&QListWidget::itemChanged,this,&MainWindow::onItemChanged);

    Timer = new QTimer(this);
    connect(Timer, &QTimer::timeout, this, &MainWindow::refreshNodeList); //timer to refrest the list if the ant node running if it that can be added to the list 
    Timer->start(500ms);

}

MainWindow::~MainWindow()
{
    delete ui;
}

std::shared_ptr<Qtros> MainWindow::getNode(){
    std::cout<<"started"<<std::endl;
    return qtros;
 
}


void MainWindow::pages(int row)
{
    // std::cout<<"Selected row"<<std::endl;
    if (row == 0) {
        ui->stackedWidget->setCurrentIndex(row);
    }
    else if (row == 1) {
        ui->stackedWidget->setCurrentIndex(row);
        refreshNodeList();
    }
    else if (row == 2) {
        ui->stackedWidget->setCurrentIndex(row);
    }
    else if (row == 3) {
        ui->stackedWidget->setCurrentIndex(row);
    }
    else if (row == 4) {
        ui->stackedWidget->setCurrentIndex(row);
    }
}

void MainWindow::refreshNodeList()
{
    // std::cout << "5678" << std::endl;

    auto get_nodes = qtros->get_node_names();
    for (auto &node : get_nodes) {
        QString qnode = QString::fromStdString(node);
        qnode = qnode.trimmed().remove("/");
        node = qnode.toStdString();
    }

    // Block signals to prevent onItemChanged from firing
    // when we programmatically add/remove items
    ui->node_list->blockSignals(true);

    // Build a QSet of active nodes for fast lookup
    QSet<QString> activeNodes;
    for (const auto &node : get_nodes) {
        activeNodes.insert(QString::fromStdString(node));
    }

    // 🔹 Add new nodes that are not already in the list
    for (const auto &node : get_nodes) {
        QString qnode = QString::fromStdString(node);  //qnode "the nodes listed in the node_list is called qnode"
        bool exists = false;

        for (int i = 0; i < ui->node_list->count(); i++) {
            if (ui->node_list->item(i)->text() == qnode) {  
                exists = true;
                break; // Stop searching once found
            }
        }

        if (!exists) {
            QListWidgetItem *item = new QListWidgetItem(qnode, ui->node_list);
            item->setFlags(item->flags() | Qt::ItemIsUserCheckable);
            item->setCheckState(Qt::Unchecked);
        }
    }

    // 🔹 Remove nodes that are no longer running
    // Iterate in reverse to safely delete while looping
    for (int i = ui->node_list->count() - 1; i >= 0; i--) {
        QListWidgetItem *item = ui->node_list->item(i);
        if (!activeNodes.contains(item->text())) {
            // Also remove from clicked_node map if it was checked
            std::string nodeName = item->text().toStdString();

            if (clicked_node.find(nodeName) != clicked_node.end()) { //Not every node in the list was checked by the user
            //So before erasing, we check if it even EXISTS in the map
                clicked_node.erase(nodeName);
            }

            delete ui->node_list->takeItem(i);
        }
    }

    // Re-enable signals after all programmatic changes are done
    ui->node_list->blockSignals(false);
}

void MainWindow::onItemChanged(QListWidgetItem *item)
{
    // std::cout << "1234" << std::endl;

    QString nodeName = item->text();
    qDebug()<<nodeName ;
    std::string node = nodeName.toStdString();

    if (item->checkState() == Qt::Checked) {
        // Insert into map only if not already present
        if (clicked_node.find(node) == clicked_node.end()) {
            clicked_node.insert({node});
        }
        std::cout << "Checked: " << node << "\n";
    }
    else if (item->checkState() == Qt::Unchecked) {
        // Remove from map only if present
        if (clicked_node.find(node) != clicked_node.end()) {
            clicked_node.erase(node);
        }
        std::cout << "Unchecked: " << node << "\n";
    }
}

void MainWindow::onLogReceived(const QString &msg,const QString &name,int level)
{
    if (clicked_node.find(name.toStdString())!=clicked_node.end()){
        QString logMessage = QString("[%1] %2: %3").arg(msg)
                                                .arg(name)
                                                .arg(level);
        if (level >= 40) {
            ui->plainTextEdit_3->appendPlainText(logMessage); // ERROR
        }
        else if (level >= 30) {
            ui->plainTextEdit_2->appendPlainText(logMessage); // WARN
        }
        else {
            ui->plainTextEdit->appendPlainText(logMessage);   // INFO
        }
    }
}

