#include "mainwindow.h"
#include "ui_mainwindow.h"
#include <iostream>
#include <QProcess>
#include <QListWidget>
#include <QListWidgetItem>
#include <QDebug>
#include <QString>
#include <QDebug>
#include <rviz_common/visualization_manager.hpp>
#include <OgreSceneManager.h>
#include <OgreException.h>
#include <OGRE/Overlay/OgreOverlayManager.h>

using namespace std::chrono_literals;

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow)//This is a class auto-generated by Qt
                                                //Comes from your .ui file 
{
    ui->setupUi(this);
    connect(ui->listWidget, &QListWidget::currentRowChanged, // Sidebar → Page Switching
            this, [=](int row){
                pages(row);
            });
    ui->listWidget->setCurrentRow(0); //Default page

    qtros = std::make_shared<Qtros>();
    connect(qtros.get(),&Qtros::logReceived,this,&MainWindow::onLogReceived);// once the message is received from the subscription in qtros, 
    // it will emit a signal logReceived which is connected to the onLogReceived slot in MainWindow.
   
    ros_node_mapping =
        std::make_shared<rviz_common::ros_integration::RosNodeAbstraction>(
            "rviz_internal_mappingnode"
        );
    ros_weak = ros_node_mapping;
    rivz_clock = std::make_shared<rclcpp::Clock>(RCL_ROS_TIME);

    render_panel_1 = new rviz_common::RenderPanel();
    toolbar = new QToolBar(ui->widget_4);
    layout = qobject_cast<QVBoxLayout*>(ui->widget_4->layout());
    layout = new QVBoxLayout(ui->widget_4);
    ui->widget_4->setLayout(layout);
    visual_manager(render_panel_1, ros_weak, rivz_clock);

    connect(ui->node_list,&QListWidget::itemChanged,this,&MainWindow::onItemChanged);

    Timer = new QTimer(this);
    connect(Timer, &QTimer::timeout, this, &MainWindow::refreshNodeList); //timer to refrest the list if the ant node running if it that can be added to the list 
    Timer->start(500ms);

}

MainWindow::~MainWindow()
{
    delete ui;
}

std::shared_ptr<Qtros> MainWindow::getNode(){
    std::cout<<"started"<<std::endl;
    return qtros;
 
}


void MainWindow::pages(int row)
{
    // std::cout<<"Selected row"<<std::endl;
    if (row == 0) {
        ui->stackedWidget->setCurrentIndex(row);
    }

    else if (row == 1) {
        ui->stackedWidget->setCurrentIndex(row);
        refreshNodeList();
    }

    else if (row == 2) {
         ui->stackedWidget->setCurrentIndex(row);
            // // if (!rviz_initialized_mapping) {
                initRViz_mapping();
            //     // rviz_initialized_mapping = true;
            // // }         
    }
    else if (row == 3) {
        ui->stackedWidget->setCurrentIndex(row);
        initRViz_navigation();
    }

    else if (row == 4) {
        ui->stackedWidget->setCurrentIndex(row);
            initRViz_localization();
    }
}

void MainWindow::refreshNodeList()
{

    auto get_nodes = qtros->get_node_names();
    for (auto &node : get_nodes) {
        QString qnode = QString::fromStdString(node);
        qnode = qnode.trimmed().remove("/");
        node = qnode.toStdString();
    }

    // Block signals to prevent onItemChanged from firing
    // when we programmatically add/remove items
    ui->node_list->blockSignals(true);

    // Build a QSet of active nodes for fast lookup
    QSet<QString> activeNodes;
    for (const auto &node : get_nodes) {
        activeNodes.insert(QString::fromStdString(node));
    }

    // 🔹 Add new nodes that are not already in the list
    for (const auto &node : get_nodes) {
        QString qnode = QString::fromStdString(node);  //qnode "the nodes listed in the node_list is called qnode"
        bool exists = false;

        for (int i = 0; i < ui->node_list->count(); i++) {
            if (ui->node_list->item(i)->text() == qnode) {  
                exists = true;
                break; // Stop searching once found
            }
        }

        if (!exists) {
            QListWidgetItem *item = new QListWidgetItem(qnode, ui->node_list);
            item->setFlags(item->flags() | Qt::ItemIsUserCheckable);
            item->setCheckState(Qt::Unchecked);
        }
    }

    // 🔹 Remove nodes that are no longer running
    // Iterate in reverse to safely delete while looping
    for (int i = ui->node_list->count() - 1; i >= 0; i--) {
        QListWidgetItem *item = ui->node_list->item(i);
        if (!activeNodes.contains(item->text())) {
            // Also remove from clicked_node map if it was checked
            std::string nodeName = item->text().toStdString();

            if (clicked_node.find(nodeName) != clicked_node.end()) { //Not every node in the list was checked by the user
            //So before erasing, we check if it even EXISTS in the map
                clicked_node.erase(nodeName);
            }

            delete ui->node_list->takeItem(i);
        }
    }

    // Re-enable signals after all programmatic changes are done
    ui->node_list->blockSignals(false);
}

void MainWindow::onItemChanged(QListWidgetItem *item)
{
    QString nodeName = item->text();
    qDebug()<<nodeName ;
    std::string node = nodeName.toStdString();

    if (item->checkState() == Qt::Checked) {
        // Insert into map only if not already present
        if (clicked_node.find(node) == clicked_node.end()) {
            clicked_node.insert({node});
        }
        std::cout << "Checked: " << node << "\n";
    }
    else if (item->checkState() == Qt::Unchecked) {
        // Remove from map only if present
        if (clicked_node.find(node) != clicked_node.end()) {
            clicked_node.erase(node);
        }
        std::cout << "Unchecked: " << node << "\n";
    }
}

void MainWindow::onLogReceived(const QString &msg,const QString &name,int level)
{
    if (clicked_node.find(name.toStdString())!=clicked_node.end()){
        QString logMessage = QString("[%1] %2: %3").arg(msg)
                                                .arg(name)
                                                .arg(level);
        if (level >= 40) {
            ui->plainTextEdit_3->appendPlainText(logMessage); // ERROR
        }
        else if (level >= 30) {
            ui->plainTextEdit_2->appendPlainText(logMessage); // WARN
        }
        else {
            ui->plainTextEdit->appendPlainText(logMessage);   // INFO
        }
    }
}

void MainWindow::visual_manager(
    rviz_common::RenderPanel* visual_panel, 
    std::weak_ptr<rviz_common::ros_integration::RosNodeAbstractionIface> ros_weak_ptr, // Added "Iface"
    rclcpp::Clock::SharedPtr sys_clock) // Simplified Clock type 
{   
    this->winId();
    render_panel_1->winId();
    QApplication::processEvents();

    render_panel_1->getRenderWindow()->initialize(); // Initialize the Ogre window for this panel
    QApplication::processEvents();
    if(!visualizationManager_){
        visualizationManager_ = new rviz_common::VisualizationManager(
            visual_panel,
            ros_weak_ptr,
            nullptr,
            sys_clock );
        visualizationManager_->initialize(); 
        render_panel_1->initialize(visualizationManager_); 
    }

    auto *tool_manager = visualizationManager_->getToolManager();

    tool_manager->addTool(
        "rviz_default_plugins/MoveCamera");

    tool_manager->setCurrentTool(tool_manager->getTool(
            tool_manager->numTools() - 1));

    cleaning_points_plugins = tool_manager->addTool(
            "rviz_default_plugins/PublishPoint");

    goal_pose_plugins =tool_manager->addTool(
            "rviz_default_plugins/SetGoal");

    pose_estimate_plugins =tool_manager->addTool(
            "rviz_default_plugins/SetInitialPose");

    connect(Cleaning_Points, &QAction::triggered, this, [=]()
    {
        if (cleaning_points_plugins)
            tool_manager->setCurrentTool(cleaning_points_plugins);
    });

    connect(Goal_Pose, &QAction::triggered, this, [=]()
    {
        if (goal_pose_plugins)
            tool_manager->setCurrentTool(goal_pose_plugins);
    });

    connect(Pose_Estimate, &QAction::triggered, this, [=]()
    {
        if (pose_estimate_plugins)   
            tool_manager->setCurrentTool(pose_estimate_plugins);
    });

    visualizationManager_->startUpdate(); 
}

void MainWindow::initRViz_mapping()
{  
    layout->addWidget(toolbar);
    layout->addWidget(render_panel_1);
    setupDisplays();
}

void MainWindow::setupDisplays()
{
    visualizationManager_->setFixedFrame("map");

    auto *grid = visualizationManager_->createDisplay(
        "rviz_default_plugins/Grid", "Grid", true);
    Q_UNUSED(grid);

    auto *laser = visualizationManager_->createDisplay(
        "rviz_default_plugins/LaserScan", "LaserScan", true);
    if (laser)
        laser->subProp("Topic")->setValue("/scan");

    auto *map = visualizationManager_->createDisplay(
        "rviz_default_plugins/Map", "Map", true);
    if (map)
        map->subProp("Topic")->setValue("/map");
}

void MainWindow::initRViz_navigation()
{ 
    QVBoxLayout *layout =
        qobject_cast<QVBoxLayout*>(ui->widget_3->layout());
    // Safely converts (casts) that generic layout pointer into a specific Vertical Layout pointer.
    // If widget_3 is actually using a QHBoxLayout or QGridLayout, this returns 'nullptr'.

    if (!layout) {
        layout = new QVBoxLayout(ui->widget_3);
        ui->widget_3->setLayout(layout);
    }
    if(!toolbar){
        layout->addWidget(toolbar);
    }

    QAction *Cleaning_Points = new QAction("Cleaning Points", this);
    QAction *Goal_Pose = new QAction("2D Goal Pose", this);
    QAction *Pose_Estimate = new QAction("2D Pose Estimate", this);
    QAction *Safty_Points = new QAction("Safety Points", this);

    toolbar->addAction(Cleaning_Points);
    toolbar->addAction(Goal_Pose);
    toolbar->addAction(Pose_Estimate);
    toolbar->addAction(Safty_Points);

        // Setup Tools
    auto *tool_manager = visualizationManager_->getToolManager();

    tool_manager->addTool(
        "rviz_default_plugins/MoveCamera");

    tool_manager->setCurrentTool(tool_manager->getTool(
            tool_manager->numTools() - 1));

    cleaning_points_plugins = tool_manager->addTool(
            "rviz_default_plugins/PublishPoint");

    goal_pose_plugins =tool_manager->addTool(
            "rviz_default_plugins/SetGoal");

    pose_estimate_plugins =tool_manager->addTool(
            "rviz_default_plugins/SetInitialPose");
   
    render_panel_1->setParent(ui->widget_3);// REUSE EXISTING RVIZ PANEL
    layout->addWidget(render_panel_1);
    
    connect(Cleaning_Points, &QAction::triggered, this, [=]()
    {
        if (cleaning_points_plugins)
            tool_manager->setCurrentTool(cleaning_points_plugins);
    });

    connect(Goal_Pose, &QAction::triggered, this, [=]()
    {
        if (goal_pose_plugins)
            tool_manager->setCurrentTool(goal_pose_plugins);
    });

    connect(Pose_Estimate, &QAction::triggered, this, [=]()
    {
        if (pose_estimate_plugins)   
            tool_manager->setCurrentTool(pose_estimate_plugins);
    });

   setupDisplays_2();
}


void MainWindow::setupDisplays_2()
{
    visualizationManager_->setFixedFrame("map");

    auto *grid2 = visualizationManager_->createDisplay(
        "rviz_default_plugins/Grid", "Grid2", true);
    Q_UNUSED(grid2);

    auto *laser = visualizationManager_->createDisplay(
        "rviz_default_plugins/LaserScan", "LaserScan", true);
    if (laser)
        laser->subProp("Topic")->setValue("/scan");

    auto *map = visualizationManager_->createDisplay(
        "rviz_default_plugins/Map", "Map", true);
    if (map)
        map->subProp("Topic")->setValue("/map");
}

void MainWindow::initRViz_localization()
{
    QVBoxLayout *layout =
        qobject_cast<QVBoxLayout*>(ui->widget_2->layout());

    if (!layout) {
        layout = new QVBoxLayout(ui->widget_2);
        ui->widget_2->setLayout(layout);
    }

    if(!toolbar){
        layout->addWidget(toolbar);

        QAction *Cleaning_Points = new QAction("Cleaning Points", this);
        QAction *Goal_Pose = new QAction("2D Goal Pose", this);
        QAction *Pose_Estimate = new QAction("2D Pose Estimate", this);
        QAction *Safty_Points = new QAction("Safety Points", this);

        toolbar->addAction(Cleaning_Points);
        toolbar->addAction(Goal_Pose);
        toolbar->addAction(Pose_Estimate);
        toolbar->addAction(Safty_Points);
    }

    render_panel_1->setParent(ui->widget_2);// REUSE EXISTING RVIZ PANEL
    layout->addWidget(render_panel_1);

    auto *tool_manager =visualizationManager_->getToolManager();

    tool_manager->addTool(
        "rviz_default_plugins/MoveCamera");

    tool_manager->setCurrentTool(tool_manager->getTool(
        tool_manager->numTools() - 1));

    cleaning_points_plugins =tool_manager->addTool(
        "rviz_default_plugins/PublishPoint");

    goal_pose_plugins =tool_manager->addTool(
        "rviz_default_plugins/SetGoal");

    pose_estimate_plugins =tool_manager->addTool(
        "rviz_default_plugins/SetInitialPose");

    // Connections
    connect(Cleaning_Points, &QAction::triggered, this, [=]()
    {
        if (cleaning_points_plugins)
            tool_manager->setCurrentTool(cleaning_points_plugins);
    });

    connect(Goal_Pose, &QAction::triggered, this, [=]()
    {
        if (goal_pose_plugins)
            tool_manager->setCurrentTool(goal_pose_plugins);
    });

    connect(Pose_Estimate, &QAction::triggered, this, [=]()
    {
        if (pose_estimate_plugins)   
            tool_manager->setCurrentTool(pose_estimate_plugins);
    });

    setupDisplays_3();  
}

void MainWindow::setupDisplays_3()
{
    visualizationManager_->setFixedFrame("map");

    auto *grid2 = visualizationManager_->createDisplay(
        "rviz_default_plugins/Grid", "Grid2", true);
    Q_UNUSED(grid2);

    auto *laser = visualizationManager_->createDisplay(
        "rviz_default_plugins/LaserScan", "LaserScan", true);
    if (laser)
        laser->subProp("Topic")->setValue("/scan");

    auto *map = visualizationManager_->createDisplay(
        "rviz_default_plugins/Map", "Map", true);
    if (map)
        map->subProp("Topic")->setValue("/map");
}
