#include "mainwindow.h"
#include "ui_mainwindow.h"
#include <iostream>
#include <QProcess>
#include <QListWidget>
#include <QListWidgetItem>
#include <QDebug>
#include <QString>


using namespace std::chrono_literals;

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow)//This is a class auto-generated by Qt
                                                //Comes from your .ui file 
{

    ui->setupUi(this);
    connect(ui->listWidget, &QListWidget::currentRowChanged, // Sidebar → Page Switching
            this, [=](int row){
                pages(row);
    });
    ui->listWidget->setCurrentRow(0); //Default page

    qtros = std::make_shared<Qtros>();
    connect(qtros.get(),&Qtros::logReceived,this,&MainWindow::onLogReceived);// once the message is received from the subscription in qtros, 
    // it will emit a signal logReceived which is connected to the onLogReceived slot in MainWindow.

    connect(ui->node_list,&QListWidget::itemChanged,this,&MainWindow::onItemChanged);

    Timer = new QTimer(this);
    connect(Timer, &QTimer::timeout, this, &MainWindow::refreshNodeList); //timer to refrest the list if the ant node running if it that can be added to the list 
    Timer->start(500ms);

}

MainWindow::~MainWindow()
{
    delete ui;
}

std::shared_ptr<Qtros> MainWindow::getNode(){
    std::cout<<"started"<<std::endl;
    return qtros;
 
}


void MainWindow::pages(int row)
{
    if (row == 0) {
        ui->stackedWidget->setCurrentIndex(row);
    }
    else if (row == 1) {
        ui->stackedWidget->setCurrentIndex(row);
        // refreshNodeList();
    }
    else if (row == 2) {
        ui->stackedWidget->setCurrentIndex(row);
    }
    else if (row == 3) {
        ui->stackedWidget->setCurrentIndex(row);
    }
    else if (row == 4) {
        ui->stackedWidget->setCurrentIndex(row);
    }
}


void MainWindow::refreshNodeList()
{
    QProcess process;
    process.start("ros2", QStringList() << "node" << "list");
    process.waitForFinished();

    QString output = process.readAllStandardOutput();
    QStringList nodes = output.split("\n", Qt::SkipEmptyParts);

    // 🔹 Add new nodes
    for (const QString &node : nodes) {

        bool exists = false;
        for (int i = 0; i < ui->node_list->count(); i++) { 
            //Qt the initial condition here are no items to check 
            // exists remains false then we add the new node 
            if (ui->node_list->item(i)->text() == node) {
                exists = true;
                // break;
            }
        }
        if (!exists) {
            QListWidgetItem *item = new QListWidgetItem(node, ui->node_list);
            item->setFlags(item->flags() | Qt::ItemIsUserCheckable); 
            //it used to create the checkbox using the flags()
            item->setCheckState(Qt::Unchecked);
        }
    }//

    // 🔹 Remove stopped nodes
    for (int i = ui->node_list->count() - 1; i >= 0; i--) { //checks from the revers index {node_list count()-1}

        QListWidgetItem *item = ui->node_list->item(i);

        if (!nodes.contains(item->text())) {
            delete ui->node_list->takeItem(i);
        }
    }
}

void MainWindow::onItemChanged(QListWidgetItem *item)
{
    QString nodename =item->text();
    std::string node =nodename.toStdString();
    int index =ui->node_list->row(item);

    if (item->checkState() == Qt::Checked) {
        if(clicked_node.find(node) == clicked_node.end())
        {
            clicked_node.insert({node, index}); 
        }
        std::cout << "Checked : " << "\n";

    } 
    else {
        if (item->checkState() == Qt::Unchecked) {
            if(clicked_node.find(node) != clicked_node.end())
            {
                clicked_node.erase(node);
            }
            std::cout << "Unchecked : " << "\n";
        }
    }
}


void MainWindow::onLogReceived(const QString &msg,const QString &name,int level)
{
    if (clicked_node.find(name.toStdString())!=clicked_node.end()){
        QString logMessage = QString("[%1] %2: %3").arg(msg)
                                                .arg(name)
                                                .arg(level);
        if (level >= 40) {
            ui->plainTextEdit_3->appendPlainText(logMessage); // ERROR
        }
        else if (level >= 30) {
            ui->plainTextEdit_2->appendPlainText(logMessage); // WARN
        }
        else {
            ui->plainTextEdit->appendPlainText(logMessage);   // INFO
        }
    }
}