string CREATE="create"
string ACTIVATE="activate"
string DEACTIVATE="deactivate"
string CLEANUP="cleanup"
string DESTROY="destroy"

string component_name
string state

---
string SUCCESS="success"
string FAILED="failed"

string result
string result_description